# Generated by Django 4.2.20 on 2025-04-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_category_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.TextField(),
        ),
    ]
