# Generated by Django 4.2.20 on 2025-04-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_budget_category_alter_budget_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='monthly_budget',
            new_name='amount',
        ),
    ]
